export { default as FadeAnimation } from './Fade.animation'
export { default as FadeUpAnimation } from './FadeUp.animation'
export { default as NewFadeUpAnimation } from './NewFade.animation'
export { default as SlideUpAnimation } from './Slideup.animation'
export { default as TextAnimation } from './Text.animation'
